PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user (
  idUser INTEGER NOT NULL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS thread (
  idThread INTEGER NOT NULL PRIMARY KEY,
  title TEXT NOT NULL,
  author_idUser INTEGER NOT NULL,
  FOREIGN KEY (author_idUser) REFERENCES user(idUser) 
);

CREATE TABLE IF NOT EXISTS message (
  idMessage INTEGER NOT NULL PRIMARY KEY,
  data TEXT NOT NULL,
  idThread INTEGER NOT NULL,
  FOREIGN KEY (idThread) REFERENCES thread(idThread) 
);