PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user (
  idUser INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS thread (
  idThread INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  author_idUser INTEGER NOT NULL,
  FOREIGN KEY (author_idUser) REFERENCES user(idUser)
);

CREATE TABLE IF NOT EXISTS message (
  idMessage INTEGER PRIMARY KEY AUTOINCREMENT,
  data TEXT NOT NULL,
  idThread INTEGER NOT NULL,
  FOREIGN KEY (idThread) REFERENCES thread(idThread)
);